graphite:
  build: graphite
  container_name: graphite
  ports:
    - "8080:80"
    - "2003-2004:2003-2004"
    - "2023-2024:2023-2024"
    - "8125:8125/udp"
    - "8126:8126"
  volumes:
    - graphite-date:/opt/graphite
grafana:
  image: "grafana/grafana"
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - graphite:graphite
  volumes:
    - grafana-storage:/var/lib/grafana
