---

- name: copy mysql config files
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    backup: yes
    force: yes
  notify:
    - restart mysql

- name: Create new mysql database
  mysql_db:
    name: '{{ wp_db_name }}'
    state: present

- name: Create new mysql user for wordpress
  mysql_user:
    name: '{{ item.user }}'
    host: '{{ item.host }}'
    password: '{{ wp_db_passwd }}'
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
  loop:
    - { user: '{{ wp_db_user}}', host: "localhost" }
    - { user: '{{ wp_db_user}}', host: "127.0.0.1" }
    - { user: '{{ wp_db_user}}', host: "%" }
