---
- name: Create new mysql database
  mysql_db:
    name: {{ wp_db_name }}
    state: present

- name: Create new mysql user for wordpress
  mysql_user:
    name: {{ wp_db_user }}
    password: {{ wp_db_passwd }}
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
