---
- name: check if docker is installed
  raw: "docker --version"
  register: docker_installed
  ignore_errors: yes

- name: install docker
  include: install.yaml
  when: docker_installed | failed

- name: start graphite/grafana docker container
  include: configure.yaml
